# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

 steps:
   # ich  checke zuerst das Repository aus

    - uses: actions/checkout@v2

    # ich richte die benötigte Umgebung ein.

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: "14.x"

    # Abhaengigkeiten

    - name: Install dependencies
      run: npm install

    - name: Run test
      run: npm test

    - name: Install modules
      run: yarn

    # run eslint
    - name: Run ESLint
      run: eslint . --ext .js,.jsx,.ts,.tsx

      # compress
    - name: Brotli compress the html, css and js files in repository
      id: brotli
      uses: charlesworth/compress-action@1.0
